global using Xunit;
global using FluentAssertions;
global using AutoMapper;
global using Moq;
global using Calmska.Api;
global using Microsoft.AspNetCore.Mvc.Testing;
global using Microsoft.EntityFrameworkCore;
global using System.Net.Http.Json;
global using System.Net;